steps:
- name: 'ubuntu'
  args: ['bash', '-c', 'apt-get update && apt-get install -y make && apt-get install -y curl && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && apt-cache policy docker-ce && apt-get install -y docker-ce &&  make compile']
  dir: 'src/mail'
- name: 'ubuntu'
  args: ['bash', '-c', '/usr/bin/make compile']
  dir: 'src/mail'
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/lax-gateway/mail:$REVISION_ID", "."]
  dir: 'src/mail/tmp'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/lax-gateway/mail:$REVISION_ID"]
